import { useState, useEffect } from 'react';
import axios from 'axios';
import { AlertOctagon, RefreshCw, ServerCrash } from 'lucide-react';
import { toast } from '../utils/toast';

export default function Error() {
    const [errors, setErrors] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchErrors = () => {
        setLoading(true);
        axios.get('http://localhost:8000/admin/logs/errors')
            .then(res => {
                if (res.data?.status === 'success') {
                    setErrors(res.data.data || []);
                } else {
                    toast.error("Failed to load error telemetry.");
                }
            })
            .catch(() => toast.error("Network Error: Backend Offline"))
            .finally(() => setLoading(false));
    };

    useEffect(() => {
        fetchErrors();
    }, []);

    return (
        <div className="flex flex-col h-full max-w-5xl mx-auto">
            <header className="flex items-center justify-between mb-6 shrink-0">
                <div>
                    <h2 className="text-2xl font-bold text-slate-800 tracking-tight flex items-center gap-3">
                        <span className="p-2 bg-rose-50 rounded-xl text-rose-500"><AlertOctagon size={20} /></span>
                        System Error Telemetry
                    </h2>
                    <p className="text-slate-500 mt-1 text-sm font-medium">Global crash reports and exception traces generated by operational modules.</p>
                </div>
                <button
                    onClick={fetchErrors}
                    className="bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 font-semibold px-4 py-2 text-sm rounded-lg flex items-center gap-2 transition-all shadow-sm"
                >
                    <RefreshCw size={16} className={loading ? "animate-spin" : ""} /> Refresh
                </button>
            </header>

            <div className="flex-1 overflow-hidden flex flex-col bg-white rounded-3xl border border-slate-100 shadow-xl shadow-slate-200/50 relative">
                <div className="flex-1 overflow-y-auto p-6">
                    {loading ? (
                        <div className="flex items-center justify-center h-full text-slate-400 font-medium animate-pulse text-lg">Scanning Error Nodes...</div>
                    ) : errors.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-full text-center">
                            <div className="bg-emerald-50 p-6 rounded-full border border-emerald-100 mb-4">
                                <svg className="w-12 h-12 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            <h3 className="text-xl font-bold text-slate-700">Zero System Errors</h3>
                            <p className="text-slate-500 mt-2 max-w-xs">All modules and telemetry pipelines are currently operating nominally with no crash vectors detected.</p>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {errors.map((e, idx) => (
                                <div key={idx} className="bg-rose-50/50 border border-rose-100 p-5 rounded-2xl shadow-sm relative group hover:border-rose-200 transition-colors">
                                    <div className="flex items-center justify-between mb-3 border-b border-rose-100/50 pb-3">
                                        <div className="flex items-center gap-2">
                                            <ServerCrash size={18} className="text-rose-400" />
                                            <span className="font-bold text-rose-800 text-sm uppercase tracking-wider">{e.source} Module</span>
                                        </div>
                                        <div className="bg-white text-rose-500 font-mono text-xs px-3 py-1 rounded shadow-sm border border-rose-100">
                                            {e.datetime}
                                        </div>
                                    </div>
                                    <p className="text-sm text-slate-700 font-mono bg-white p-4 rounded-xl border border-rose-50 leading-relaxed overflow-x-auto shadow-inner shadow-slate-100/50">
                                        {e.error_message}
                                    </p>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
